### ISSUE TITLE
Caching resources

### ISSUE THREAD

**Issue by mxplusb** [cloudfoundry-incubator/cfdev#113]
It would be awesome if there was a way to cache the downloaded resources so when you run `cf dev start` it can first check to see if there are locally available assets before attempting to download them.

For example, I wanted to test a theory with bosh while I'm in a public place, and it's trying to download all of the assets on public wifi.

**Comment by aemengo** [comment]
@mxplusb Perhaps the output is misleading but that is the exact behavior of `cf dev start`. If the assets are already present locally, it will prefer using them over attempting to re-download.

Another possible source of confusion is that it performs a checksum validation on an locally present assets, which can take some time due to actual size of the assets.

**Comment by mxplusb** [comment]
@aemengo if that's the existing behaviour, I think the output could be a little misleading.
