### ISSUE TITLE
`cf dev start/stop` calls `bosh start/stop-vm`

### ISSUE THREAD

**Issue by mxplusb** [cloudfoundry-incubator/cfdev#122]
It would be a very nice feature to have `cf dev` be able to start and stop the virtual machine without having to deploy the entire stack. I do quite like that `cf dev start` is idempotent, but I also would like to be able to start and stop the virtual machine for a reboot without having to take a 15-20 minute time penalty while it deploys the stack from scratch.

In my head, I could see this functionality:

* `cf dev deploy`: wipe the slate (if it exists), idempotent init deployment.
* `cf dev start`: starts a stopped virtual machine and invokes `bosh start-vm` on all the internal components.
* `cf dev stop`: invokes `bosh stop-vm` on all of the internal components and then stops the virtual machine.
* `cf dev destroy`: stops and destroys the virtual machine.

That would be super helpful for folks who run it on laptops who will have to start and stop it for both battery and usage reasons (walking from point a to b, etc.)

**Comment by aemengo** [comment]
Hi there, thanks for the feedback on the product.

While this has come up before and we certainly sympathize with the desire to avoid the 15-20 minute time penalty, there are simply too many architectural obstacles in the way of delivering `start/stop` or `suspend/resume` functionality. The reason is, ultimately, that the CF Dev VM leverages and behaves just like a Docker Desktop solution, which also doesn't have the ability. Please keep in mind that the time delay isn't from setting up the VM itself, but from provisioning all the containers inside - and this would take the same amount time whether `bosh stop-vm` was called or not.  

https://github.com/cloudfoundry-incubator/cfdev/issues/54#issuecomment-461918656
