### ISSUE TITLE
As a CF Dev user, I can start CF Dev on Linux

### ISSUE THREAD

**Issue by ssisil** [cloudfoundry-incubator/cfdev#18]
**Acceptance Criteria**

**Scenario : Start CF Dev on Linux**

**GIVEN** I installed the cfdev linux binary as a CF CLI plugin
**WHEN** I run cf dev start
**THEN** I see the following output in my terminal
```
Downloading Resources...
Deploying the BOSH Director...
Deploying CF...

  ██████╗███████╗██████╗ ███████╗██╗   ██╗
 ██╔════╝██╔════╝██╔══██╗██╔════╝██║   ██║
 ██║     █████╗  ██║  ██║█████╗  ██║   ██║
 ██║     ██╔══╝  ██║  ██║██╔══╝  ╚██╗ ██╔╝
 ╚██████╗██║     ██████╔╝███████╗ ╚████╔╝
  ╚═════╝╚═╝     ╚═════╝ ╚══════╝  ╚═══╝
             is now running!

To begin using CF Dev, please run:
    cf login -a https://api.v3.pcfdev.io --skip-ssl-validation

Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass
```
**AND** CATS (for PCF) passes
**AND** I can target the VM BOSH director with v3.pcfdev.io (or any route, given that it's a wildcard)
**AND** CF Dev will be started without a VM or VPNKit

**Scenario 2 : Set os in segment to Linux**

**GIVEN** A user has opted in to collecting telemetry
**WHEN** CF Dev is started on a Linux machine
**THEN** all segment telemetry calls will set the OS to Linux

---
**Developer Notes**
- NO_PROXY, HTTP_PROXY and HTTPS_PROXY need to be respected

**Comment by BenHall** [comment]
Thanks for opening the issue. I was speaking with @chipchilders about this. We have a distinct use-case for where CFDev is essential. 

What needs to happen in order to port CFDev from MacOS to Linux? I noticed you are building on top of Linuxkit, does this mean the VM is already running on linux? Is it the cfdev-v0.0.1-darwin that would need to be recompiled?

**Comment by dgodd** [comment]
Hi @BenHall ,

CF currently always needs to run on linux machines, so yes on the mac we start a linux VM to run CF on and then proxy the relevant ports. 

We have been looking at linux support in multiple ways.
1. Start a VM and run it in that
2. Run CF on the host machine using containerization instead of a seperate VM. (using garden for the containerization)

I personally prefer the latter approach, but it has certain issues around differing kernels. Neither plan is trivial and require a fair amount of work (much more than recompiling sadly). We are currently starting on windows support.

Would you mind discussing your use-case?

**Comment by BenHall** [comment]
The scenario is to use Katacoda.com (of which I'm the founder of) to help people understand the CF workflow and how to get started. Katacoda is an interactive learning platform for software developers, available via the browser without any downloads or configuration. You can see what we're doing with Kubernetes at https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/.  

CF-Dev will make this possible and we could showcase it via the Katacoda platform.

Both VM and Containers work for us. We can pin the container to a particular kernel version if that makes life easier.

**Comment by sclevine** [comment]
That's awesome! Can you provide more details about how you plan to use CF Dev for this?

The CF Dev VM currently requires 4GB+ RAM, and it's not designed for multi-tenant use (ex. default credentials are everywhere). If you aren't trying to teach platform operator functionality, a single large deployment of CF could make more sense.

**Comment by chipchilders** [comment]
@sclevine I spoke with @BenHall about this at kubecon. The general idea (and I'll let him correct me here) is that they stand up small environments for the various tools / platforms that they offer training around for each student. Seems like cfdev would be a good way to potentially do that, given the small size.

**Comment by richard-cox** [comment]
We over at @cloudfoundry-incubator/stratos-ui would love to use cfdev on linux. We're currently using pcfdev for development and test, however we've heard that's now end of life and would love to make the switch to the new bits in cfdev. Would it be possible to understand how this feature is going and any possible timelines?

**Comment by andrelohmann** [comment]
Any progress on this? When will cfdev come to linux machines too?

**Comment by ssisil** [comment]
@andrelohmann - This is something we have prioritized in our backlog. We are currently working on implementing significant performance improvements for our current versions. Once that is complete we will start the linux version (which will include the performance improvements). Look for something here in the coming months.

**Comment by aemengo** [comment]
@richard-cox Our plans for linux support haven't changed. This was closed because this is a (non-trivial) feature request, as opposed to an issue. We'd rather not have GitHub issues for tracking long-running feature requests.

**Comment by chipchilders** [comment]
Is there a link to a tracker story or epic that people can watch?

**Comment by sdawson-pivotal** [comment]
On second thought, we think keeping this issue open will be the most efficient way for folks to follow it's progress. Re-opening.

**Comment by joaompinto** [comment]
Hi,
because I also had the need  of using a CF environment on Linux for lab purposes, I have created a set of scripts that should be sufficient for creating a lab. In any case, a CFDev (vm/containerized) approach is a better option.

If possible please share the branch/repo that you will be using for the Linux support, I would like to be able to collaborate on that.

The links for the scripts:
https://github.com/CCSGroupInternational/cf-linux-lab-setup

**Comment by aemengo** [comment]
Version 0.0.15 released with support for the linux platform. Find out more info here: https://github.com/cloudfoundry-incubator/cfdev/releases/tag/v0.0.15
