### ISSUE TITLE
is there a way to suspend cfdev? 

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry-incubator/cfdev#54]
cf dev stop destroy the VM, is there a way to suspend cfdev? Thanks

**Comment by ssisil** [comment]
Hi @betht1220 - we do not support this currently - but are working on adding this in an upcoming release. Will update this thread when this is available.

**Comment by sdawson-pivotal** [comment]
@betht1220 would you mind sharing a bit about your use case? We are looking to better understand how people are using CF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1

**Comment by krishbiswas** [comment]
@sdawson-pivotal have taken the survey. Thanks. Any update on the request here on this thread? Would be great have the ability to start/stop the VM w/out destroying it completely.

**Comment by aemengo** [comment]
@krishbiswas I'd like to address the concerns around suspend/resume since it has come up before. The architecture of CF Dev is largely dependent on the Docker (Docker Desktop). Thus, core VM features like suspend/resume would have to come from upstream before we could easily incorporate it.

That being said, perhaps a better way to track the progress of this feature is to see when they can address it for their product:
https://github.com/moby/hyperkit/issues/20

**Comment by antechrestos** [comment]
@sdawson-pivotal I don't know if it is still time but I also completed the survey

**Comment by dmytropetryk** [comment]
> Hi @betht1220 - we do not support this currently - but are working on adding this in an upcoming release. Will update this thread when this is available.

Hi, @ssisil do you have any updates regarding support of `suspend/resume` feature?

**Comment by ssisil** [comment]
Hi @dmytropetryk - I have not been closely involved with the project over the past year.  Tagging @aemengo - do you know if this feature made it into cfdev?
