### ISSUE TITLE
cf release manifest

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry-incubator/cfdev#58]
Can you post the url to the cf release manifest that is used when "cf dev start" runs.
I have delete the existing cf deployment and want to deploy an exact release
Thanks

**Comment by aemengo** [comment]
Hi! Unfortunately, we do not host the cf release manifest anywhere since it is generated during the build process. However, it is pretty easy to retrieve if you have a cfdev up and running, as posted [here](https://github.com/cloudfoundry/bosh/issues/2074#issuecomment-436077471), you can do:

```
$ eval "$(cf dev bosh env)"
$ bosh -d cf manifest > ./cf.yml
```
However, unfortunately Github issues is not the best platform for the sequential nature of questions that you're asking. We'll be very happy to provide more real-time assistance in the '#pcfdev' channel in https://cloudfoundry.slack.com. You've already posted there, so it's is completely our fault for not keeping a closer eye on it. We promise to do so now.

**Comment by sdawson-pivotal** [comment]
@betht1220 would you mind sharing a bit about your use case? We are looking to better understand how people are using CF / PCF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1
