### ISSUE TITLE
PCF Dev: cf create-service p.rabbitmq solo my_rabbit fails with both solo and cluster plans

### ISSUE THREAD

**Issue by codeaches** [cloudfoundry-incubator/cfdev#71]
In PCF Dev, the `cf create-service p.rabbitmq solo my_rabbit` fails with both solo and cluster plans.

The log error is as shown below.
Note: PCF dev was started using the command `cf dev start -c 12 -m 18432 -f pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz`. I have also used the command `cf install-plugin -r CF-Community "cfdev"` before starting the `cf dev`.

**Error in log**
```log
vpnkit.exe: [ERROR] Socket.UDPv4.write udp:68.105.28.12:53: caught A socket operation was attempted to an unreachable network.
```

**Also, the plans available with and without `-s scs` for rabbitmq is different. The plans for `p-rabbitmq` with option `-s scs` enabled is `standard`. The plan for `p.rabbitmq` available without `-s scs` enabled is `solo` and `cluster`. Is this intentional?**

Could you please look into these errors? I have attached the log for your reference.

[deploy-rabbitmq.log](https://github.com/cloudfoundry-incubator/cfdev/files/2793308/deploy-rabbitmq.log)
[org.cloudfoundry.cfdev.vpnkit.wrapper.log](https://github.com/cloudfoundry-incubator/cfdev/files/2793310/org.cloudfoundry.cfdev.vpnkit.wrapper.log)
[deploy-cf.log](https://github.com/cloudfoundry-incubator/cfdev/files/2793311/deploy-cf.log)
[org.cloudfoundry.cfdev.vpnkit.err.log](https://github.com/cloudfoundry-incubator/cfdev/files/2793312/org.cloudfoundry.cfdev.vpnkit.err.log)

Thanks,
Pavan

**Comment by codeaches** [comment]
Ok, thank you. Just curious to know if there any work around while your team looks into it?

Thanks,
Pavan

**Comment by aemengo** [comment]
@codeaches We're not able to reproduce this issue. What does the CF CLI output say (on the terminal window), when it fails.

> Also, the plans available with and without -s scs for rabbitmq is different. The plans for p-rabbitmq with option -s scs enabled is standard. The plan for p.rabbitmq available without -s scs enabled is solo and cluster. Is this intentional?

Yes this is intentional. The `p-rabbitmq` and `p.rabbitmq` services that CF Dev provides are somewhat different. `p.rabbitmq` is default rabbitmq, which can be explicitly enabled with the `-s rabbitmq` flag or with a standard start. This is the rabbitmq that will contain the *solo* and *cluster* plans and that we expect to be consumed. The `p-rabbitmq` refers the [rabbitmq multitenant release](https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release). This is deployed as primarily a dependency to `scs`.

**Comment by aemengo** [comment]
@codeaches We're not able to reproduce this issue. What does the CF CLI output say (on the terminal window), when it fails.

```
C:\Users\pivotal\Downloads> cf service my_rabbit
.....

status:    create succeeded
```

> Also, the plans available with and without -s scs for rabbitmq is different. The plans for p-rabbitmq with option -s scs enabled is standard. The plan for p.rabbitmq available without -s scs enabled is solo and cluster. Is this intentional?

Yes this is intentional. The `p-rabbitmq` and `p.rabbitmq` services that CF Dev provides are somewhat different. `p.rabbitmq` is default rabbitmq, which can be explicitly enabled with the `-s rabbitmq` flag or with a standard start. This is the rabbitmq that will contain the *solo* and *cluster* plans and that we expect to be consumed. The `p-rabbitmq` refers the [rabbitmq multitenant release](https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release). This is deployed as primarily a dependency to `scs`.

**Comment by codeaches** [comment]
@aemengo , this is the error I get when I execute `cf service my_rabbit1`. It's the same error for both `solo` and `cluster`. 

```log
PS C:\pcf_suite> cf service my_rabbit1
Showing info of service my_rabbit1 in org cfdev-org / space cfdev-space as admin...

name:            my_rabbit1
service:         p.rabbitmq
tags:
plan:            cluster
description:     RabbitMQ Dedicated Instance
documentation:
dashboard:       https://rmq-8a275e2c-91e6-4a8d-9356-3ca67d85df26.dev.cfdev.sh

Showing status of last operation from service my_rabbit1...

status:    create failed
message:   Instance provisioning failed: There was a problem completing your request. Please contact your operations team providing the following information: service: p.rabbitmq,
           service-instance-guid: 8a275e2c-91e6-4a8d-9356-3ca67d85df26, broker-request-id: 4841ed93-b4ed-4bc3-9c74-d3b5557e6a69, task-id: 1075, operation: create
started:   2019-01-26T07:07:25Z
updated:   2019-01-26T07:12:28Z

There are no bound apps for this service.
```
